import express, { Request, Response } from 'express';
import fs from 'fs';
import path from 'path';
import projectManager from '../services/projectManager';

const router = express.Router();

// GET /api/plugins - List plugins and their status
router.get('/', (req: Request, res: Response) => {
  try {
    const pluginsDir = path.join(projectManager.getJsPath(), 'plugins');
    if (!fs.existsSync(pluginsDir)) return res.json({ plugins: [], list: [] });

    // Read plugins.js for enabled list
    const pluginsJsPath = path.join(projectManager.getJsPath(), 'plugins.js');
    let pluginList: { name: string; status: boolean; description: string; parameters: Record<string, string> }[] = [];
    if (fs.existsSync(pluginsJsPath)) {
      const content = fs.readFileSync(pluginsJsPath, 'utf8');
      const match = content.match(/\$plugins\s*=\s*(\[[\s\S]*?\]);/);
      if (match) {
        try { pluginList = JSON.parse(match[1]); } catch {}
      }
    }

    // List all .js files in plugins/
    const files = fs.readdirSync(pluginsDir).filter(f => f.endsWith('.js')).map(f => f.replace('.js', ''));

    res.json({ files, list: pluginList });
  } catch (err: unknown) {
    res.status(500).json({ error: (err as Error).message });
  }
});

// PUT /api/plugins - Save plugin list
router.put('/', (req: Request, res: Response) => {
  try {
    const pluginsJsPath = path.join(projectManager.getJsPath(), 'plugins.js');
    const content = `// Generated by RPG Maker MV Editor\nvar $plugins = ${JSON.stringify(req.body, null, 2)};\n`;
    fs.writeFileSync(pluginsJsPath, content, 'utf8');
    res.json({ success: true });
  } catch (err: unknown) {
    res.status(500).json({ error: (err as Error).message });
  }
});

export default router;
